// Seed script to import real production data from Puffs.
// Generated by Codex.

import { PrismaClient, ProductionRole, RehearsalStatus, Role } from "@prisma/client";
import { readFileSync } from "node:fs";
import { join } from "node:path";
import { zonedToUtc } from "../src/lib/availabilityTime.ts";

const prisma = new PrismaClient();

const SEED_NAMESPACE = "puffs-historical-seed";
const SEED_DIR = join(process.cwd(), "seed");
const SEED_ORGANISATION_ID = `seed-org-${SEED_NAMESPACE}`;
const SEED_PRODUCTION_ID = `seed-production-${SEED_NAMESPACE}`;
const SEED_DIRECTOR_ID = `seed-user-${SEED_NAMESPACE}-director`;
const SEED_EMAIL_DOMAIN = "seed.local";
const DEFAULT_TIME_ZONE = "America/New_York";
const DEFAULT_TARGET_ORGANISATION_NAME = "Opera House Players";
const DEFAULT_WEEKDAY_START = "19:00";
const DEFAULT_WEEKDAY_END = "22:00";
const DEFAULT_WEEKEND_START = "13:00";
const DEFAULT_WEEKEND_END = "17:00";
const SEED_OWNER_EMAIL = process.env.SEED_OWNER_EMAIL?.trim().toLowerCase() || null;
const SEED_TARGET_ORGANISATION_ID =
  process.env.SEED_TARGET_ORGANISATION_ID?.trim() || null;
const SEED_TARGET_ORGANISATION_NAME =
  process.env.SEED_TARGET_ORGANISATION_NAME?.trim() ||
  DEFAULT_TARGET_ORGANISATION_NAME;

type Mode = "seed" | "revert";

type CastMemberRow = {
  performer_id: string;
  performer_name: string;
  roles: string;
};

type ConflictRow = {
  performer_name: string;
  conflict_raw: string;
  start_date: string;
  end_date: string;
  recurrence: string;
  note: string;
};

type SceneBlockRow = {
  block_id: string;
  scene_name: string;
  estimated_pages: string;
};

type SceneCastRequirementRow = {
  scene_name: string;
  performer_name: string;
  character_or_note: string;
};

type ScheduleEventRow = {
  event_id: string;
  source_sheet: string;
  source_cell: string;
  rehearsal_date: string;
  weekday: string;
  start_time: string;
  end_time: string;
  rehearsal_title: string;
  scenes_raw: string;
  not_called_raw: string;
  comment_author: string;
};

type ScheduleItemRow = {
  event_id: string;
  source_sheet: string;
  rehearsal_date: string;
  scene_name_raw: string;
  scene_name_key: string;
};

type Counts = {
  users: number;
  memberships: number;
  productionMembers: number;
  availabilityWindows: number;
  schedulingDrafts: number;
  productionRehearsals: number;
  rehearsalParticipants: number;
};

function parseBooleanEnv(value: string | undefined, fallback: boolean) {
  if (value === undefined) {
    return fallback;
  }

  const normalized = value.trim().toLowerCase();
  if (["1", "true", "yes", "y", "on"].includes(normalized)) {
    return true;
  }
  if (["0", "false", "no", "n", "off"].includes(normalized)) {
    return false;
  }

  return fallback;
}

function parseMode(value: string | undefined): Mode {
  if (!value) {
    return "seed";
  }

  const normalized = value.trim().toLowerCase();
  if (normalized === "seed" || normalized === "revert") {
    return normalized;
  }

  throw new Error("MODE must be either seed or revert.");
}

function parseCsv(content: string) {
  const rows: string[][] = [];
  let row: string[] = [];
  let field = "";
  let quoted = false;

  for (let index = 0; index < content.length; index += 1) {
    const char = content[index];
    const next = content[index + 1];

    if (quoted) {
      if (char === "\"" && next === "\"") {
        field += "\"";
        index += 1;
      } else if (char === "\"") {
        quoted = false;
      } else {
        field += char;
      }
      continue;
    }

    if (char === "\"") {
      quoted = true;
    } else if (char === ",") {
      row.push(field);
      field = "";
    } else if (char === "\n") {
      row.push(field.replace(/\r$/, ""));
      rows.push(row);
      row = [];
      field = "";
    } else {
      field += char;
    }
  }

  if (field.length > 0 || row.length > 0) {
    row.push(field.replace(/\r$/, ""));
    rows.push(row);
  }

  return rows.filter((candidate) => candidate.some((value) => value.trim().length > 0));
}

function readCsv<T extends Record<string, string>>(fileName: string): T[] {
  const rows = parseCsv(readFileSync(join(SEED_DIR, fileName), "utf8"));
  const header = rows[0];

  if (!header) {
    throw new Error(`${fileName} is empty.`);
  }

  return rows.slice(1).map((row) =>
    Object.fromEntries(header.map((key, index) => [key, row[index] ?? ""])) as T
  );
}

function userIdForPerformerId(performerId: string) {
  return `seed-user-${SEED_NAMESPACE}-${performerId}`;
}

function emailForPerformerId(performerId: string) {
  return `${performerId}@${SEED_EMAIL_DOMAIN}`;
}

function parseLocalDate(value: string) {
  const match = value.trim().match(/^(\d{4})-(\d{2})-(\d{2})$/);
  if (!match) {
    return null;
  }

  return {
    year: Number(match[1]),
    month: Number(match[2]),
    day: Number(match[3]),
  };
}

function parseLocalTime(value: string) {
  const match = value.trim().match(/^(\d{1,2}):(\d{2})$/);
  if (!match) {
    return null;
  }

  return {
    hour: Number(match[1]),
    minute: Number(match[2]),
  };
}

function addDays(date: { year: number; month: number; day: number }, days: number) {
  const utc = new Date(Date.UTC(date.year, date.month - 1, date.day + days));
  return {
    year: utc.getUTCFullYear(),
    month: utc.getUTCMonth() + 1,
    day: utc.getUTCDate(),
  };
}

function localDateToKey(date: { year: number; month: number; day: number }) {
  return `${date.year.toString().padStart(4, "0")}-${date.month
    .toString()
    .padStart(2, "0")}-${date.day.toString().padStart(2, "0")}`;
}

function localDateTimeToUtc(
  date: { year: number; month: number; day: number },
  time: string,
  timeZone: string
) {
  const parsedTime = parseLocalTime(time);
  if (!parsedTime) {
    throw new Error(`Invalid local time: ${time}`);
  }

  const utc = zonedToUtc(
    {
      ...date,
      hour: parsedTime.hour,
      minute: parsedTime.minute,
    },
    timeZone,
    { rejectNonexistent: true }
  );

  if (!utc) {
    throw new Error(`Unable to convert ${localDateToKey(date)} ${time} in ${timeZone}.`);
  }

  return utc;
}

function fullLocalDayWindow(date: { year: number; month: number; day: number }, timeZone: string) {
  return {
    start: localDateTimeToUtc(date, "00:00", timeZone),
    end: localDateTimeToUtc(addDays(date, 1), "00:00", timeZone),
  };
}

function inclusiveDateRange(startValue: string, endValue: string) {
  const start = parseLocalDate(startValue);
  const end = parseLocalDate(endValue);
  if (!start || !end) {
    return [];
  }

  const dates = [];
  for (let cursor = start; localDateToKey(cursor) <= localDateToKey(end); cursor = addDays(cursor, 1)) {
    dates.push(cursor);
  }
  return dates;
}

function weekdayName(date: { year: number; month: number; day: number }) {
  return new Intl.DateTimeFormat("en-US", {
    timeZone: "UTC",
    weekday: "long",
  }).format(new Date(Date.UTC(date.year, date.month - 1, date.day)));
}

function normalizeSceneName(value: string) {
  return value
    .trim()
    .toUpperCase()
    .replace(/\([^)]*\)/g, " ")
    .replace(/&/g, " AND ")
    .replace(/\bB4\b/g, "BEFORE")
    .replace(/\b1ST\b/g, "FIRST")
    .replace(/\bYR\b/g, "YEAR")
    .replace(/\bRM\b/g, "ROOM")
    .replace(/^REVIEW\s+/, "")
    .replace(/[^A-Z0-9]+/g, " ")
    .replace(/\s+/g, " ")
    .trim();
}

const SCENE_ALIASES = new Map<string, string>([
  ["WELCOME TO PUFFS", "WELCOME TO THE PUFFS"],
  ["THE FEAST", "THE FEAST!"],
  ["BACK IN THE COMMON ROOM", "BACK IN THE COMMON RM"],
  ["YEAR 2", "YEAR TWO"],
  ["YEAR TWO", "YEAR TWO"],
  ["YEAR 3", "YEAR THREE"],
  ["YEAR THREE", "YEAR THREE"],
  ["DAYS BEFORE THE FIRST TASK", "DAYS B4 THE 1ST TASK"],
  ["FIRST TASK", "THE FIRST TASK"],
  ["THIRD TASK", "THE THIRD TASK"],
  ["START OF ACT II", "ACT II"],
  ["A FUNERAL AND AN IM", "A FUNERAL AND IM"],
  ["A FUNERAL IM", "A FUNERAL AND IM"],
  ["A FUNERAL AND IM", "A FUNERAL AND IM"],
  ["GOBLETS FIRES", "GOBLETS. FIRES."],
  ["GOBLETS FIRES ADD IN BELLA LINDA", "GOBLETS. FIRES."],
  ["HOPKINS POTTER EMOTIONS", "HOPKINS, POTTER&EMOTIONS"],
  ["HOPKINS POTTER AND EMOTIONS", "HOPKINS, POTTER&EMOTIONS"],
  ["LATER IN THE HALLWAY", "LATER, IN THE HALLWAY"],
  ["THE MUMMY", "MUMMY"],
  ["END OF YEAR 6", "END OF YR 6"],
  ["A GREAT HALL AGAIN", "A GREAT HALL AGAIN"],
  ["A VERY WHITE ROOM", "A VERY WHITE RM"],
  ["WAYNE CEDRIC", "WAYNE&CEDRIC"],
  ["WAYNE AND CEDRIC", "WAYNE&CEDRIC"],
  ["WAYNE CEDRIC 2", "WAYNE&CEDRIC"],
  ["WAYNE AND CEDRIC 2", "WAYNE&CEDRIC"],
  ["19 YEARS LATER", "19 YEARS BLAH BLAH"],
  ["THE END OF THE YEAR AGAIN", "END OF YEAR AGAIN"],
]);

function canonicalSceneName(value: string) {
  const normalized = normalizeSceneName(value);
  const alias = SCENE_ALIASES.get(normalized);
  return alias ? normalizeSceneName(alias) : normalized;
}

function parseNameList(value: string) {
  return value
    .split(",")
    .map((entry) => entry.trim())
    .filter(Boolean);
}

function namesFromNotCalled(value: string, castRows: CastMemberRow[]) {
  const byFirstName = new Map(
    castRows.map((row) => [row.performer_name.split(/\s+/)[0]?.toLowerCase(), row.performer_name])
  );

  return parseNameList(value)
    .map((entry) => byFirstName.get(entry.toLowerCase()) ?? entry)
    .filter((entry) => castRows.some((row) => row.performer_name === entry));
}

function durationMinutesFromPages(value: string) {
  const pages = Number.parseFloat(value);
  if (!Number.isFinite(pages) || pages <= 0) {
    return 15;
  }

  return Math.max(15, Math.ceil((pages * 15) / 15) * 15);
}

function buildConflictWindows({
  conflicts,
  castByName,
  timeZone,
}: {
  conflicts: ConflictRow[];
  castByName: Map<string, CastMemberRow>;
  timeZone: string;
}) {
  const windows: Array<{
    userId: string;
    start: Date;
    end: Date;
    source: ConflictRow;
  }> = [];

  for (const conflict of conflicts) {
    const castMember = castByName.get(conflict.performer_name);
    if (!castMember) {
      continue;
    }

    if (conflict.start_date && conflict.end_date) {
      for (const date of inclusiveDateRange(conflict.start_date, conflict.end_date)) {
        windows.push({
          userId: userIdForPerformerId(castMember.performer_id),
          ...fullLocalDayWindow(date, timeZone),
          source: conflict,
        });
      }
    }

    if (conflict.recurrence === "Tuesdays") {
      for (const date of inclusiveDateRange("2024-01-07", "2024-04-14")) {
        if (weekdayName(date) === "Tuesday") {
          windows.push({
            userId: userIdForPerformerId(castMember.performer_id),
            ...fullLocalDayWindow(date, timeZone),
            source: conflict,
          });
        }
      }
    }

    if (conflict.recurrence === "Sunday; Monday; Wednesday through February") {
      for (const date of inclusiveDateRange("2024-01-07", "2024-02-29")) {
        if (["Sunday", "Monday", "Wednesday"].includes(weekdayName(date))) {
          windows.push({
            userId: userIdForPerformerId(castMember.performer_id),
            ...fullLocalDayWindow(date, timeZone),
            source: conflict,
          });
        }
      }
    }
  }

  const deduped = new Map<string, (typeof windows)[number]>();
  for (const window of windows) {
    deduped.set(
      `${window.userId}:${window.start.toISOString()}:${window.end.toISOString()}`,
      window
    );
  }

  return [...deduped.values()];
}

function buildSceneRequirements({
  rows,
  castByName,
}: {
  rows: SceneCastRequirementRow[];
  castByName: Map<string, CastMemberRow>;
}) {
  const requirements = new Map<string, Set<string>>();

  for (const row of rows) {
    const castMember = castByName.get(row.performer_name);
    if (!castMember) {
      continue;
    }

    const scene = canonicalSceneName(row.scene_name);
    const existing = requirements.get(scene) ?? new Set<string>();
    existing.add(userIdForPerformerId(castMember.performer_id));
    requirements.set(scene, existing);
  }

  return requirements;
}

function buildSchedulingDraftBlocks({
  sceneBlocks,
  sceneRequirements,
}: {
  sceneBlocks: SceneBlockRow[];
  sceneRequirements: Map<string, Set<string>>;
}) {
  const seenBlockIds = new Map<string, number>();

  return sceneBlocks.map((sceneBlock) => {
    const baseId = sceneBlock.block_id.trim() || normalizeSceneName(sceneBlock.scene_name).toLowerCase();
    const currentCount = seenBlockIds.get(baseId) ?? 0;
    seenBlockIds.set(baseId, currentCount + 1);
    const clientId = currentCount === 0 ? baseId : `${baseId}_${currentCount + 1}`;

    return {
      clientId,
      label: sceneBlock.scene_name.trim(),
      durationMinutes: String(durationMinutesFromPages(sceneBlock.estimated_pages)),
      requiredPeopleIds: [...(sceneRequirements.get(canonicalSceneName(sceneBlock.scene_name)) ?? [])],
      predecessorBlockIds: [],
    };
  });
}

function eventTimeWindow(event: ScheduleEventRow, timeZone: string) {
  const date = parseLocalDate(event.rehearsal_date);
  if (!date) {
    throw new Error(`Invalid rehearsal_date for ${event.event_id}`);
  }

  const isWeekend = event.weekday === "Saturday" || event.weekday === "Sunday";
  const startTime = event.start_time || (isWeekend ? DEFAULT_WEEKEND_START : DEFAULT_WEEKDAY_START);
  const endTime = event.end_time || (isWeekend ? DEFAULT_WEEKEND_END : DEFAULT_WEEKDAY_END);

  return {
    start: localDateTimeToUtc(date, startTime, timeZone),
    end: localDateTimeToUtc(date, endTime, timeZone),
    inferredTimes: !event.start_time || !event.end_time,
  };
}

function buildManualRehearsals({
  events,
  items,
  castRows,
  sceneRequirements,
  timeZone,
}: {
  events: ScheduleEventRow[];
  items: ScheduleItemRow[];
  castRows: CastMemberRow[];
  sceneRequirements: Map<string, Set<string>>;
  timeZone: string;
}) {
  const finalEvents = events.filter((event) => event.source_sheet === "Final Schedule");
  const itemsByEvent = new Map<string, ScheduleItemRow[]>();

  for (const item of items.filter((candidate) => candidate.source_sheet === "Final Schedule")) {
    const eventItems = itemsByEvent.get(item.event_id) ?? [];
    eventItems.push(item);
    itemsByEvent.set(item.event_id, eventItems);
  }

  return finalEvents.map((event) => {
    const eventItems = itemsByEvent.get(event.event_id) ?? [];
    const requiredUserIds = new Set<string>();
    const unmatchedScenes: string[] = [];

    for (const item of eventItems) {
      const canonical = canonicalSceneName(item.scene_name_key || item.scene_name_raw);
      const sceneCast = sceneRequirements.get(canonical);

      if (!sceneCast) {
        unmatchedScenes.push(item.scene_name_raw || item.scene_name_key);
        continue;
      }

      for (const userId of sceneCast) {
        requiredUserIds.add(userId);
      }
    }

    for (const notCalled of namesFromNotCalled(event.not_called_raw, castRows)) {
      const castMember = castRows.find((row) => row.performer_name === notCalled);
      if (castMember) {
        requiredUserIds.delete(userIdForPerformerId(castMember.performer_id));
      }
    }

    if (event.scenes_raw.toLowerCase().includes("full cast")) {
      for (const castMember of castRows) {
        requiredUserIds.add(userIdForPerformerId(castMember.performer_id));
      }
    }

    const timeWindow = eventTimeWindow(event, timeZone);

    return {
      event,
      start: timeWindow.start,
      end: timeWindow.end,
      inferredTimes: timeWindow.inferredTimes,
      participantUserIds: [...requiredUserIds],
      unmatchedScenes,
      itemScenes: eventItems.map((item) => item.scene_name_raw),
    };
  });
}

async function countSeedRows(): Promise<Counts> {
  const rehearsalIds = (
    await prisma.productionRehearsal.findMany({
      where: { productionId: SEED_PRODUCTION_ID },
      select: { id: true },
    })
  ).map((rehearsal) => rehearsal.id);

  const [
    users,
    memberships,
    productionMembers,
    availabilityWindows,
    schedulingDrafts,
    productionRehearsals,
    rehearsalParticipants,
  ] = await Promise.all([
    prisma.user.count({ where: { id: { startsWith: `seed-user-${SEED_NAMESPACE}` } } }),
    prisma.membership.count({
      where: { userId: { startsWith: `seed-user-${SEED_NAMESPACE}` } },
    }),
    prisma.productionMember.count({ where: { productionId: SEED_PRODUCTION_ID } }),
    prisma.availabilityWindow.count({ where: { productionId: SEED_PRODUCTION_ID } }),
    prisma.schedulingDraft.count({ where: { productionId: SEED_PRODUCTION_ID } }),
    prisma.productionRehearsal.count({ where: { productionId: SEED_PRODUCTION_ID } }),
    rehearsalIds.length > 0
      ? prisma.rehearsalParticipant.count({ where: { rehearsalId: { in: rehearsalIds } } })
      : Promise.resolve(0),
  ]);

  return {
    users,
    memberships,
    productionMembers,
    availabilityWindows,
    schedulingDrafts,
    productionRehearsals,
    rehearsalParticipants,
  };
}

function printCounts(counts: Counts, verb: string) {
  console.log(`  ${verb} users: ${counts.users}`);
  console.log(`  ${verb} organisation memberships: ${counts.memberships}`);
  console.log(`  ${verb} production members: ${counts.productionMembers}`);
  console.log(`  ${verb} conflict windows: ${counts.availabilityWindows}`);
  console.log(`  ${verb} scheduling drafts: ${counts.schedulingDrafts}`);
  console.log(`  ${verb} manual schedule rehearsals: ${counts.productionRehearsals}`);
  console.log(`  ${verb} rehearsal participant rows: ${counts.rehearsalParticipants}`);
}

async function revertSeedData(dryRun: boolean) {
  const counts = await countSeedRows();

  if (!dryRun) {
    await prisma.$transaction(async (tx) => {
      await tx.production.deleteMany({ where: { id: SEED_PRODUCTION_ID } });
      // Backward-compatible cleanup for earlier runs that created a throwaway org.
      await tx.organisation.deleteMany({ where: { id: SEED_ORGANISATION_ID } });
      await tx.user.deleteMany({
        where: { id: { startsWith: `seed-user-${SEED_NAMESPACE}` } },
      });
    });
  }

  return counts;
}

async function seedData(dryRun: boolean) {
  const castRows = readCsv<CastMemberRow>("cast_members.csv");
  const conflicts = readCsv<ConflictRow>("conflicts.csv");
  const sceneBlocks = readCsv<SceneBlockRow>("scene_blocks.csv");
  const sceneCastRows = readCsv<SceneCastRequirementRow>("scene_cast_requirements.csv");
  const events = readCsv<ScheduleEventRow>("rehearsal_schedule_events.csv");
  const items = readCsv<ScheduleItemRow>("rehearsal_schedule_items.csv");
  const timeZone = process.env.SEED_TIME_ZONE?.trim() || DEFAULT_TIME_ZONE;
  const ownerUser = SEED_OWNER_EMAIL
    ? await prisma.user.findUnique({
        where: {
          email: SEED_OWNER_EMAIL,
        },
        select: {
          id: true,
          email: true,
          name: true,
        },
      })
    : null;
  const targetOrganisation = SEED_TARGET_ORGANISATION_ID
    ? await prisma.organisation.findUnique({
        where: { id: SEED_TARGET_ORGANISATION_ID },
        select: { id: true, name: true },
      })
    : await prisma.organisation.findFirst({
        where: { name: SEED_TARGET_ORGANISATION_NAME },
        select: { id: true, name: true },
        orderBy: { createdAt: "asc" },
      });

  if (SEED_OWNER_EMAIL && !ownerUser) {
    throw new Error(
      `SEED_OWNER_EMAIL=${SEED_OWNER_EMAIL} does not match an existing user. Log in once, then rerun.`
    );
  }

  if (!targetOrganisation) {
    throw new Error(
      SEED_TARGET_ORGANISATION_ID
        ? `SEED_TARGET_ORGANISATION_ID=${SEED_TARGET_ORGANISATION_ID} does not match an existing organisation.`
        : `Could not find organisation named "${SEED_TARGET_ORGANISATION_NAME}". Set SEED_TARGET_ORGANISATION_ID or SEED_TARGET_ORGANISATION_NAME.`
    );
  }

  const directorUserId = ownerUser?.id ?? SEED_DIRECTOR_ID;
  const existingDirectorMembership = ownerUser
    ? await prisma.membership.findUnique({
        where: {
          userId_organisationId: {
            userId: ownerUser.id,
            organisationId: targetOrganisation.id,
          },
        },
        select: { id: true },
      })
    : null;

  if (ownerUser && !existingDirectorMembership) {
    throw new Error(
      `${ownerUser.email} is not a member of "${targetOrganisation.name}". Use an existing organisation admin/member login, or omit SEED_OWNER_EMAIL for a synthetic seed director.`
    );
  }

  const castByName = new Map(castRows.map((row) => [row.performer_name, row]));
  const sceneRequirements = buildSceneRequirements({ rows: sceneCastRows, castByName });
  const draftBlocks = buildSchedulingDraftBlocks({ sceneBlocks, sceneRequirements });
  const conflictWindows = buildConflictWindows({ conflicts, castByName, timeZone });
  const manualRehearsals = buildManualRehearsals({
    events,
    items,
    castRows,
    sceneRequirements,
    timeZone,
  });

  const previewCounts: Counts = {
    users: castRows.length + (ownerUser ? 0 : 1),
    memberships: castRows.length + (ownerUser ? 0 : 1),
    productionMembers: castRows.length + 1,
    availabilityWindows: conflictWindows.length,
    schedulingDrafts: 1,
    productionRehearsals: manualRehearsals.length,
    rehearsalParticipants: manualRehearsals.reduce(
      (total, rehearsal) => total + rehearsal.participantUserIds.length,
      0
    ),
  };

  const unmatchedScenes = [
    ...new Set(manualRehearsals.flatMap((rehearsal) => rehearsal.unmatchedScenes)),
  ];

  if (!dryRun) {
    await revertSeedData(false);

    await prisma.$transaction(
      async (tx) => {
        if (!ownerUser) {
          await tx.user.create({
            data: {
              id: SEED_DIRECTOR_ID,
              name: "Seed Director",
              email: `director@${SEED_EMAIL_DOMAIN}`,
              emailVerified: true,
            },
          });
        }

        if (!ownerUser) {
          await tx.membership.create({
            data: {
              organisationId: targetOrganisation.id,
              userId: directorUserId,
              role: Role.ADMIN,
            },
          });
        }

        await tx.production.create({
          data: {
            id: SEED_PRODUCTION_ID,
            name: "Puffs Historical Seed",
            description: "Historical CSV import for generated-vs-manual schedule comparison.",
            rehearsalStart: localDateTimeToUtc({ year: 2024, month: 1, day: 7 }, "00:00", timeZone),
            rehearsalEnd: localDateTimeToUtc({ year: 2024, month: 4, day: 14 }, "23:59", timeZone),
            timeZone,
            venue: "CSV import",
            directorRoles: [ProductionRole.DIRECTOR],
            organisationId: targetOrganisation.id,
          },
        });

        await tx.productionMember.create({
          data: {
            productionId: SEED_PRODUCTION_ID,
            userId: directorUserId,
            role: ProductionRole.DIRECTOR,
            conflictsSubmittedAt: new Date(),
          },
        });

        for (const castMember of castRows) {
          const userId = userIdForPerformerId(castMember.performer_id);

          await tx.user.create({
            data: {
              id: userId,
              name: castMember.performer_name,
              email: emailForPerformerId(castMember.performer_id),
              emailVerified: true,
            },
          });

          await tx.membership.create({
            data: {
              organisationId: targetOrganisation.id,
              userId,
              role: Role.MEMBER,
            },
          });

          await tx.productionMember.create({
            data: {
              productionId: SEED_PRODUCTION_ID,
              userId,
              role: ProductionRole.CAST,
              conflictsSubmittedAt: new Date(),
            },
          });
        }

        await tx.availabilityWindow.createMany({
          data: conflictWindows.map((window) => ({
            productionId: SEED_PRODUCTION_ID,
            userId: window.userId,
            start: window.start,
            end: window.end,
            kind: "UNAVAILABLE",
          })),
        });

        await tx.schedulingDraft.create({
          data: {
            productionId: SEED_PRODUCTION_ID,
            userId: directorUserId,
            selectedTimeZone: timeZone,
            horizonStart: "2024-01-07T00:00",
            horizonEnd: "2024-04-14T23:45",
            allowedStartTime: DEFAULT_WEEKDAY_START,
            allowedEndTime: DEFAULT_WEEKDAY_END,
            blocks: draftBlocks,
          },
        });

        for (const rehearsal of manualRehearsals) {
          await tx.productionRehearsal.create({
            data: {
              productionId: SEED_PRODUCTION_ID,
              createdById: directorUserId,
              title: rehearsal.event.rehearsal_title,
              start: rehearsal.start,
              end: rehearsal.end,
              status: RehearsalStatus.PUBLISHED,
              sourceMetadata: {
                seedNamespace: SEED_NAMESPACE,
                source: "csv-manual-final-schedule",
                eventId: rehearsal.event.event_id,
                sourceSheet: rehearsal.event.source_sheet,
                sourceCell: rehearsal.event.source_cell,
                scenesRaw: rehearsal.event.scenes_raw,
                itemScenes: rehearsal.itemScenes,
                notCalledRaw: rehearsal.event.not_called_raw,
                inferredTimes: rehearsal.inferredTimes,
                unmatchedScenes: rehearsal.unmatchedScenes,
              },
              participants: rehearsal.participantUserIds.length
                ? {
                    createMany: {
                      data: rehearsal.participantUserIds.map((userId) => ({ userId })),
                      skipDuplicates: true,
                    },
                  }
                : undefined,
            },
          });
        }
      },
      {
        maxWait: 10_000,
        timeout: 60_000,
      }
    );
  }

  return {
    counts: previewCounts,
    timeZone,
    ownerUser,
    targetOrganisation,
    unmatchedScenes,
    draftBlocksWithoutCast: draftBlocks.filter((block) => block.requiredPeopleIds.length === 0),
  };
}

async function main() {
  const dryRun = parseBooleanEnv(process.env.DRY_RUN, true);
  const mode = parseMode(process.env.MODE);

  console.log("CSV production seed");
  console.log(`Mode: ${mode}`);
  console.log(`Dry run: ${dryRun}`);
  console.log(`Seed production id: ${SEED_PRODUCTION_ID}`);

  if (mode === "revert") {
    const counts = await revertSeedData(dryRun);
    printCounts(counts, dryRun ? "would remove" : "removed");
    return;
  }

  const result = await seedData(dryRun);
  console.log(`Time zone: ${result.timeZone}`);
  console.log(
    `Target organisation: ${result.targetOrganisation.name} (${result.targetOrganisation.id})`
  );
  console.log(
    `Seed owner: ${
      result.ownerUser
        ? `${result.ownerUser.name} <${result.ownerUser.email}>`
        : "synthetic seed director (not log-in capable)"
    }`
  );
  printCounts(result.counts, dryRun ? "would create" : "created");

  if (result.unmatchedScenes.length > 0) {
    console.log("");
    console.log("Manual schedule scenes without exact scene-block matches:");
    for (const scene of result.unmatchedScenes.slice(0, 30)) {
      console.log(`  - ${scene}`);
    }
    if (result.unmatchedScenes.length > 30) {
      console.log(`  ... ${result.unmatchedScenes.length - 30} more`);
    }
  }

  if (result.draftBlocksWithoutCast.length > 0) {
    console.log("");
    console.log("Draft blocks without cast requirements:");
    for (const block of result.draftBlocksWithoutCast) {
      console.log(`  - ${block.label}`);
    }
  }

  if (dryRun) {
    console.log("");
    console.log("Apply with: DRY_RUN=false npm run seed:csv-production");
    console.log(
      "Apply for your login with: SEED_OWNER_EMAIL=you@example.com DRY_RUN=false npm run seed:csv-production"
    );
    console.log("Revert with: MODE=revert DRY_RUN=false npm run seed:csv-production");
  }
}

main()
  .catch((error) => {
    console.error(error instanceof Error ? error.message : String(error));
    process.exitCode = 1;
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
